[package]
name = "showcase"
version = "0.0.5"
edition = "2024"
publish = false

[dependencies]
dioxus = { version = "0.7", features = ["web", "router"] }
dioxus-maplibre = { path = "../.." }
serde_json = "1"
tracing = "0.1"
