[application]
name = "showcase"
default_platform = "web"

[web.app]
title = "dioxus-maplibre showcase"

[web.resource]
style = ["https://unpkg.com/maplibre-gl@4/dist/maplibre-gl.css"]
script = ["https://unpkg.com/maplibre-gl@4/dist/maplibre-gl.js"]

[web.resource.dev]
assets = "assets"
