[application]
name = "dioxus-maplibre showcase"

[web.app]
title = "dioxus-maplibre showcase"

[web.resource.dev]
style = ["https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css"]
script = ["https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js"]
